/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Material 3 tokens straight from Stitch DESIGN.md
        surface: '#faf9fd',
        'surface-dim': '#dbd9dd',
        'surface-bright': '#faf9fd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f7',
        'surface-container': '#efedf1',
        'surface-container-high': '#e9e7eb',
        'surface-container-highest': '#e3e2e6',
        'on-surface': '#1a1b1e',
        'on-surface-variant': '#424753',
        'inverse-surface': '#2f3033',
        'inverse-on-surface': '#f1f0f4',
        outline: '#727785',
        'outline-variant': '#c2c6d5',
        primary: '#0058bd',
        'on-primary': '#ffffff',
        'primary-container': '#2771df',
        'on-primary-container': '#fefcff',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a41',
        'on-primary-fixed-variant': '#004494',
        'inverse-primary': '#adc6ff',
        secondary: '#795900',
        'on-secondary': '#ffffff',
        'secondary-container': '#febf0d',
        'on-secondary-container': '#6d5000',
        'secondary-fixed': '#ffdfa0',
        'secondary-fixed-dim': '#fbbc05',
        'on-secondary-fixed': '#261a00',
        'on-secondary-fixed-variant': '#5c4300',
        tertiary: '#006b2b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#008738',
        'on-tertiary-container': '#f7fff2',
        'tertiary-fixed': '#89fa9b',
        'tertiary-fixed-dim': '#6ddd81',
        'on-tertiary-fixed': '#002108',
        'on-tertiary-fixed-variant': '#005320',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'bg-blue': '#E8F0FE',
        'bg-yellow': '#FFF8E1',
        'bg-green': '#E6F4EA',
        'bg-red': '#FCE8E6',
        'accent-red': '#EA4335',
        'surface-card': '#FFFFFF',
        'surface-canvas': '#FAFAFA',
        'text-body': '#5F6368',
        'border-subtle': '#E0E0E0',
      },
      fontFamily: {
        lexend: ['Lexend', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'h1-hero': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'h2-section': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'h3-card': ['24px', { lineHeight: '1.4', fontWeight: '700' }],
        'body-main': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-secondary': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'stats-display': ['32px', { lineHeight: '1', fontWeight: '700' }],
      },
      spacing: {
        'section-gap': '80px',
        'grid-gap': '24px',
        'nav-height': '64px',
        'container-padding': '32px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      boxShadow: {
        card: '0 1px 3px rgba(0,0,0,0.10)',
        'card-hover': '0 8px 24px rgba(0,0,0,0.12)',
        flashcard: '0 8px 24px rgba(0,0,0,0.12)',
      },
      animation: {
        'reveal-up': 'revealUp 0.6s ease-out forwards',
        float: 'float 6s ease-in-out infinite',
        'slide-up': 'slideUp 300ms ease-out',
      },
      keyframes: {
        revealUp: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '50%': { transform: 'translateY(-20px) rotate(2deg)' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
